# baseURL = 'https://datanotes.tech/'
baseURL = 'https://datanotes8.github.io/datanotes/'
languageCode = 'en-us'
title = 'Datanotes'
theme = 'book'
googleAnalytics = "G-WH5KX5803C"

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookLogo = 'logo.png'
  BookTheme = 'light'
